name: Publish nightly build

on:
  push:
    branches:
      - main

jobs:
  nightly:
    name: Publish nightly build
    runs-on: ubuntu-latest
    environment: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      # This and --no-resign is only needed due to https://github.com/wardvl/f-droid-nightly-action/issues/3
      - name: Nightly Keystore
        run: ./nightly-keystore.py
      - name: Build
        run: ./gradlew assembleNightlyDebug
      - name: F-Droid nightly builds
        uses: wardvl/f-droid-nightly-action@v2
        with:
          debug_keystore: ${{ secrets.DEBUG_KEYSTORE }}
          fdroid_nightly_args: --no-resign --archive-older 10
